start ADR for commit signing
cloud-gov/product pull request #1673
Opened 2022-02-12 00:46 UTC by bengerman13

## Changes proposed in this pull request:
- start ADR for commit signing

## security considerations
publishing the draft ADR doesn't have security implications, but it discusses them

2022-02-15 14:49 UTC, mheadd commented on adr/ADR-0006-commit-signing.md
> +- all cloud.gov platform operators sign commits
Should we specify which kinds of repos (or specifically which repos) we would use commit signing for? Would this policy apply to commits to sample code repos, internal docs, cg-site, etc?

2022-02-15 17:20 UTC, bengerman13 commented on adr/ADR-0006-commit-signing.md
> +- all cloud.gov platform operators sign commits
I'd assume platform engineers would _sign_ all commits once we switch over; the draft instructions have you setting a param in git which causes it to sign all commits automagically, so there's no extra work there. 

We'd want to _validate_ any commits for platform repos - so everything other than cg-site, internal docs, and samples. (although, validating cg-site and internal-docs seems good, too?)

2022-02-15 17:20 UTC, bengerman13 commented on adr/ADR-0006-commit-signing.md
> +
Need to add a question about how we handle PRs that can't be rebased

2022-02-15 17:49 UTC, mheadd commented on adr/ADR-0006-commit-signing.md
> +- all cloud.gov platform operators sign commits
> although, validating cg-site and internal-docs seems good, too?

Agreed

2022-07-13 15:50 UTC, markdboyd commented on adr/ADR-0006-commit-signing.md
> +### Local validation
Do we need this section? I'm not sure if the scenario it describes is even possible. 

> Imagine a signed commit is altered with malicious content, then pushed to a branch we're working on.

This would mean commit would have to be altered with malicious intent by someone within the team, as they are the only ones with access to push commits to our repos. And if we have malicious actors within the team, we're going to have lots of problems.

2022-07-13 16:11 UTC, mogul requested changes
One set of redundant words needs removing. Other than that these are suggestions I think would be helpful to future archaeologists, though not necessarily critical to get resolved before merge.

2022-07-13 16:11 UTC, mogul commented on adr/ADR-0006-commit-signing.md
> +When a new platform operator is added, they'll generate cloud.gov-specific PGP keys.
Have we added these steps to the onboarding and offboarding checklists for operators yet? If not, we need to.

2022-07-13 16:11 UTC, mogul commented on adr/ADR-0006-commit-signing.md
> +### Local validation
I agree. We could move this section out of the `Open questions` section to explain above that "requiring signed commits on push also ensures that operators do not pull down problematic code which they might inadvertently sign+commit and then push".

2022-07-13 16:11 UTC, mogul commented on adr/ADR-0006-commit-signing.md
> +store, then reference that variable in all of our pipeline configs for git resources.
Might be good to point to an example that does this here.

2022-07-13 16:11 UTC, mogul commented on adr/ADR-0006-commit-signing.md
> +- All cloud.gov platform repos are configured to require signed commits for merging
Might be worth explicitly pointing to the Allstar config here.

2022-07-13 16:11 UTC, mogul commented on adr/ADR-0006-commit-signing.md
> +keys for platform operators
We should probably explain here that we're also accepting the GitHub signing key, for the case where it signs merges or signs on behalf of people making commits through the web UI (eg small edits to Markdown in `cg-site`. (If that is indeed the case... I can't remember if it has come up while you were working on this and since Ben left.)

2022-07-13 17:09 UTC, markdboyd commented on adr/ADR-0006-commit-signing.md
> +When a new platform operator is added, they'll generate cloud.gov-specific PGP keys.
Yes, we have:

https://github.com/cloud-gov/product/pull/1770
https://github.com/cloud-gov/product/pull/2070
https://github.com/cloud-gov/product/pull/2071

2022-07-18 20:45 UTC, mogul submitted a review, later dismissed

2022-07-18 20:47 UTC, mogul commented
Oh no...
![image](https://user-images.githubusercontent.com/47762/179614462-f83f9ef5-30bc-4329-9322-3e6a4568f8e4.png)

I guess this is an example of a case where we need to rebase in another branch/PR?

2022-07-18 20:51 UTC, merged